### ISSUE TITLE
ogt_vox: Order of input models is changes on save/load

### ISSUE THREAD

**Issue by mgerhardy** [jpaver/opengametools#21]
The order of models that I hand over to `ogt_vox_write_scene` is changed in `ogt_vox_read_scene`. It would be nice if I could disable this feature with a flag.

**Comment by mgerhardy** [comment]
https://github.com/mgerhardy/vengi/issues/113

**Comment by jpaver** [comment]
Thanks for filing the issue. Can you confirm that with the qsort removed that you get the expected behavior? If so, I'd just be inclined to remove that. Otherwise, I will have to investigate deeper when I get a bit of time.

**Comment by mgerhardy** [comment]
Yes, without the `qsort` it works fine for me.

**Comment by jpaver** [comment]
Great,  in that case I think we should just remove the sort. Callers can always do this step themselves.

**Comment by jpaver** [comment]
Closing as this has been addressed with this commit: https://github.com/jpaver/opengametools/commit/1eb03035e95ae9405a21d214dac747921d965ec4
