### ISSUE TITLE
Any writing of voxels object to Wavefront obj?

### ISSUE THREAD

**Issue by GrapixLeGrand** [jpaver/opengametools#32]
Hello,

Great project! I looked at the source code and did not find a way to write the voxels into a mesh OBJ file. Is that correct? I know Magikavoxel can do it but I want to automate this. Is this hard to implement from the current state of the project? I never really worked with it but if I have time maybe I can have a look at it? Just a bit busy right now.

Best,
Quentin

**Comment by jpaver** [comment]
As it turns out, I do have some code to do this already.  Will try clean it up and add it to the repo soon.

**Comment by GrapixLeGrand** [comment]
Okay, thanks !

**Comment by jpaver** [comment]
Hi @GrapixLeGrand -- please see commit https://github.com/jpaver/opengametools/commit/71b38f7a2478373fb89970aec0ea2e9822824051 which implements a vox2obj tool, which opens a .vox file and can extract a full frame out to an .obj file. It also supports extracting out a per-animation-frame version of each mesh if you need to reassemble it in another animation/rendering tool. 

Closing.
