### ISSUE TITLE
ogt_vox: group references broken by commit: flatten animations ...

### ISSUE THREAD

**Issue by dougbinks** [jpaver/opengametools#35]
Commit 137ff3d06a5e919cef9dcdc4fb20ec11decb9cc0 breaks the handling of group references.

Steps to reproduce:

1. Create a scene in MV with several models
2. Group the models
3. Create a reference (SHIFT+move or use icon) and move the new reference somewhere.
4. Open with ogt_vox before/after this commit. Scene is incorrect after this commit.

Example vox file: https://drive.google.com/file/d/1qpp7WUnk7_w02dCvjI0V3VTLA332dkWq/view?usp=sharing

EDIT: note that for me this fix isn't urgent as I'm able to use the previous commit plus cherry picked resize perf fix as I don't support animations for now.

**Comment by jpaver** [comment]
Thanks for the details, PR that fixes this is here: https://github.com/jpaver/opengametools/pull/36. 
I've also opened this issue (https://github.com/jpaver/opengametools/issues/37) to add formal test cases to prevent this sort of regression in the future. Thanks again!
