### ISSUE TITLE
ogt_vox: assert hit on invalid node id

### ISSUE THREAD

**Issue by mgerhardy** [jpaver/opengametools#45]
See https://github.com/mgerhardy/vengi/issues/226 - the attached vox file was also saved by ogt_vox

[assert.zip](https://github.com/jpaver/opengametools/files/10609223/assert.zip)

**Comment by jpaver** [comment]
Fix is here, would appreciate you taking a look and confirming it fixes it for you too. Thanks! https://github.com/jpaver/opengametools/pull/46
