### ISSUE TITLE
ogt_vox: looks like the transforms are not yet correctly handled

### ISSUE THREAD

**Issue by mgerhardy** [jpaver/opengametools#48]
https://github.com/Eisenwave/voxel-io/blob/master/src/format/vox.cpp
line 248ff and 353ff as well as the `divFloor` implementation might be interesting here.

There is a vox test file attached to a ticket in vengi - contributed by the voxelmax author: https://github.com/mgerhardy/vengi/issues/275

**Comment by jpaver** [comment]
Oh interesting, I wasn't aware that magicavoxel can support transform flips. I'll look into that. Thanks!

**Comment by jpaver** [comment]
Hey @mgerhardy - so I'm able to import that vox file into my own engine and it looks identical to what is visible in magicavoxel when I open it there. Is there anything particular about the way you're importing it in your vengi tools?

**Comment by mgerhardy** [comment]
hm. I only do the coordinate conversion with this matrix

```cpp
glm::mat4 {
  -1.0f, 0.0f, 0.0f, 0.0f, 
   0.0f, 0.0f, 1.0f, 0.0f, 
   0.0f, 1.0f, 0.0f, 0.0f, 
   0.0f, 0.0f, 0.0f, 1.0f
};
```

which is basically this

```cpp
glm::rotate(glm::rotate(glm::mat4(1.0f), glm::radians(-90.0f), glm::vec3(1.0f, 0.0f, 0.0f)), glm::radians(180.0f), glm::vec3(0.0f, 0.0f, 1.0f));
```

and here is my per voxel transform: 
```cpp
static inline glm::vec4 calcTransform(const glm::mat4x4 &mat, const glm::ivec3 &pos, const glm::vec4 &pivot) {
	return glm::floor(mat * (glm::vec4((float)pos.x + 0.5f, (float)pos.y + 0.5f, (float)pos.z + 0.5f, 1.0f) - pivot));
}
```

pivot is this:

```cpp
glm::vec4 pivot((float)(int)(ogtModel->size_x / 2), (float)(int)(ogtModel->size_y / 2), (float)(int)(ogtModel->size_z / 2), 0.0f);
```

I wonder if you are doing the transformation on a per-voxel basis - or if you just load the model and apply the transformation matrix to the vertices?

**Comment by mgerhardy** [comment]
this is not an issue of ogt_vox - but an issue on my side - sorry for the noise.

i've now compiled vox2obj and can see that ogt_vox handles everything correctly.
