### ISSUE TITLE
ogt_vox: segfault when accessing invalid group indices

### ISSUE THREAD

**Issue by mgerhardy** [jpaver/opengametools#55]
```cpp
for (uint32_t i = 0; i < scene->num_instances; ++i) {
  ogt_assert(scene->instances[i].group_index == k_invalid_group_index || scene->instances[i].group_index < scene->num_groups, "Invalid group index");
}
```

I've added this to the end of `ogt_vox_read_scene_with_flags` for the attached vox file - and it triggers. There is an invalid group index loaded. Maybe we should add some sanity checks to the end of this function to ensure that the client code can be safe in accessing members via index.

`vox2obj` crashes on that input file, too, Magicavoxel is able to load it

[magicavoxel.vox.zip](https://github.com/jpaver/opengametools/files/11929764/magicavoxel.vox.zip)

**Comment by mgerhardy** [comment]
oh, btw. the segfault happens in `ogt_vox_sample_instance_transform` for me, because the groups are null

**Comment by jpaver** [comment]
Hey @mgerhardy -- I took a look and pushed this PR https://github.com/jpaver/opengametools/pull/56 that fixes this issue. I would appreciate if you could take it for a spin and confirm the issues are fixed for you too. Thanks for the report!
