### ISSUE TITLE
Crashes due to unaligned memory access

### ISSUE THREAD

**Issue by mgerhardy** [jpaver/opengametools#62]
```
/home/mgerhardy/dev/engine/src/modules/voxelformat/external/ogt_vox.h:1453:55: runtime error: member access within misaligned address 0x619000005581 for type 'struct ogt_vox_keyframe_transform', which requires 4 byte alignment
0x619000005581: note: pointer points here
 00 00 00  58 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00
```

this is due to the fact that the `misc_data` allocator is configured for `char` type - which is a 1 byte alignment - but the struct `ogt_vox_keyframe_transform` is of course not aligned to 1 byte.

**Comment by jpaver** [comment]
Interesting,  that's easily fixable of course by ensuring the bump allocate rounds up sizes to a multiple of 4 bytes. Out of curiosity, can you say which cpu are you are experiencing this crash on?
